# Generated by Django 5.2.4 on 2025-07-25 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commandes', '0001_initial'),
        ('produits', '0001_initial'),
        ('utilisateurs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='adresse_facturation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes_facturation', to='utilisateurs.adresse'),
        ),
        migrations.AddField(
            model_name='commande',
            name='adresse_livraison',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes_livraison', to='utilisateurs.adresse'),
        ),
        migrations.AddField(
            model_name='commande',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='elementcommande',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='commandes.commande'),
        ),
        migrations.AddField(
            model_name='elementcommande',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produits.product'),
        ),
        migrations.AddField(
            model_name='elementcommande',
            name='variante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='produits.productvariant'),
        ),
        migrations.AddField(
            model_name='elementpanier',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produits.product'),
        ),
        migrations.AddField(
            model_name='elementpanier',
            name='variante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='produits.productvariant'),
        ),
        migrations.AddField(
            model_name='historiquestatutcommande',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_statuts', to='commandes.commande'),
        ),
        migrations.AddField(
            model_name='historiquestatutcommande',
            name='modifie_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paiement',
            name='commande',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paiement', to='commandes.commande'),
        ),
        migrations.AddField(
            model_name='panier',
            name='utilisateur',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='panier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='elementpanier',
            name='panier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='commandes.panier'),
        ),
    ]
