# Generated by Django 5.2.5 on 2025-08-11 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CentreLogistique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('adresse', models.CharField(max_length=255)),
                ('code_postal', models.CharField(max_length=20)),
                ('ville', models.CharField(max_length=100)),
                ('pays', models.CharField(max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('actif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Expedition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_suivi', models.CharField(blank=True, max_length=100, null=True)),
                ('date_expedition', models.DateTimeField(blank=True, null=True)),
                ('date_livraison_prevue', models.DateTimeField(blank=True, null=True)),
                ('date_livraison_effective', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('en_preparation', 'En préparation'), ('expediee', 'Expédiée'), ('en_transport', 'En transport'), ('livree', 'Livrée'), ('retour', 'Retour'), ('annulee', 'Annulée')], default='en_preparation', max_length=20)),
                ('commentaire', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModeLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('delai_estime', models.CharField(blank=True, max_length=100, null=True)),
                ('frais', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('actif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PreparationCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut_preparation', models.DateTimeField(blank=True, null=True)),
                ('date_fin_preparation', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('prete', 'Prête à expédier'), ('annulee', 'Annulée')], default='en_attente', max_length=20)),
                ('commentaire', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transporteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('site_web', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
            ],
        ),
    ]
