# Generated by Django 5.2.4 on 2025-07-25 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commandes', '0002_initial'),
        ('livraisons', '0001_initial'),
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expedition',
            name='adresse_livraison',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='utilisateurs.adresse'),
        ),
        migrations.AddField(
            model_name='expedition',
            name='commande',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='expedition', to='commandes.commande'),
        ),
        migrations.AddField(
            model_name='expedition',
            name='mode_livraison',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='livraisons.modelivraison'),
        ),
        migrations.AddField(
            model_name='preparationcommande',
            name='centre_logistique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='livraisons.centrelogistique'),
        ),
        migrations.AddField(
            model_name='preparationcommande',
            name='commande',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preparation', to='commandes.commande'),
        ),
        migrations.AddField(
            model_name='modelivraison',
            name='transporteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modes_livraison', to='livraisons.transporteur'),
        ),
    ]
