# Generated by Django 5.2.5 on 2025-08-11 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='logo_url',
        ),
        migrations.AddField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, default=None, help_text='Brand logo ', null=True, upload_to='brands_images/'),
        ),
    ]
