# Generated by Django 5.2.3 on 2025-07-19 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0004_stock_warehouse_alter_stock_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='warehouse',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='produits.warehouse'),
        ),
    ]
